# encrypt 加密
encrypt:
  transfer_encrypt:
    public_key:
    private_key:
  service_encrypt:
    public_key:
    private_key:
  token_encrypt:
    sign_key: Ri13J8Itaqd4g6QMLZrDNCOoXhKjFmGy
    refresh_key: suzckjGdAqvgaBSJYCyDWVxihOeP7KR6
    access_token_expire: 172800s
    refresh_token_expire: 604800s
    previous_token_expire: 60s
