# encrypt 加密
encrypt:
  transfer_encrypt:
    public_key:
    private_key:
  service_encrypt:
    public_key:
    private_key:
  token_encrypt:
    sign_key: KLmOU29y5xQtr8BZDlAwTPIigzXfFC6M
    refresh_key: kc3X4uGCUqW8Fz9NeLYHgRpQ2AKyOsJj
    access_token_expire: 172800s
    refresh_token_expire: 604800s
    previous_token_expire: 60s
