account_service:
  snowflake:
    enable: true
    instance_id: "${app.project_name}/${app.server_name}/${app.server_env}/${app.server_version}"
    instance_name: "account-service"
    metadata:
      service: account-service
  send_email_code:
    enable: true
    issuer: UUFFF
    subject: UUFFF.COM
    host: smtp.qiye.aliyun.com
    port: 465
    username: noreply@uufff.com
    password: NaeTQxpmLzb56O8H
    from: noreply@uufff.com


